import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "index",
    {
      type: "category",
      label: "Clients",
      items: [{ type: "autogenerated", dirName: "user-guide" }],
    },
    "developer-guide/contributing",
    {
      type: "category",
      label: "Release",
      items: [{ type: "autogenerated", dirName: "release" }],
    },
  ],
};

export default sidebars;
